config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'lists#index'
  resources :movies, only: %i[index show]
  # resources :movies
  # resources :bookmarks
  resources :lists do
    resources :bookmarks, only: %i[create new]
  end

  resources :bookmarks, only: %i[destroy]
  # resources :lists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  # ou faire un before_validation avec une méthode de vérif (à double conditions) ? A voir.
  validates :movie_id, presence: true, uniqueness: true
  validates :list_id, presence: true, uniqueness: true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :movies, through: :bookmarks
  has_many :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: %i[show edit update destroy]

  def index
    @bookmarks = Bookmark.all
  end

  def show
  end

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def edit
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new({ comment: bookmark_params['comment'], movie_id: bookmark_params['movie_id'], list_id: @list })
    p @bookmark
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def update
    if @bookmark.update(bookmark_params)
      redirect_to @bookmark, notice: "You bookmark was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to list_path(@bookmark.list)
  end

  private

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show edit update destroy]

  def index
    # fonctionne
    @lists = List.all
  end

  def show
  end

  def new
    # fonctionne
    @list = List.new
  end

  def edit
  end

  def create
    # fonctionne
    @list = List.new(list_params)

    if @list.save
      redirect_to @lists, notice: "You list was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @list.update(list_params)
      redirect_to @list, notice: "You list was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    # fonctionne
    @list.destroy
    redirect_to lists_url, notice: "You list was successfully destroyed."
  end

  def put_in_list
    created_list = []
    # @restaurants = Restaurant.includes(:reviews).where(reviews: { rating: 5 })
    @movies = Movie.includes(:bookmarks).where(bookmarks: true)
    created_list << @movies
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_list
    @list = List.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[show edit update destroy]

  def index
    # fonctionne
    @movies = Movie.all
  end

  def show
  end

  def new
    @movie = Movie.new
  end

  def edit
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to @movie, notice: "You movie was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @movie.update(movie_params)
      redirect_to @movie, notice: "You movie was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    # fonctionne
    @movie.destroy
    redirect_to movies_url, notice: "You movie was successfully destroyed."
  end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def list_params
    params.require(:movie).permit(:title, :overview, :poster_url, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="new-lists">
  <div class="new-list">
    <h1>Create a new <strong>bookmark</strong> !</h1>
    <%= simple_form_for [ @list, @bookmark ] do |f| %>
      <%= f.input :comment %>
      <%= f.association :movie %>
      <%= f.submit "Submit" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/lists/_list.html.erb
<div class="container">
  <p>
    <strong>Title:</strong>
    <%= list.name %>
  </p>

</div>

app/views/lists/index.html.erb
<h1>Watch List</h1>

<h2><%= "Choose your list :" %></h2>

<div>
  <% @lists.each do |list| %>
    <%= render list %>
    <p class="container">
    <%= cl_image_path @list.photo.key, height: 300, width: 400, crop: :fill %>
      <%= link_to "Show this list", list %>
    </p>
  <% end %>
</div>

<%= link_to "See all movies", movies_path %>
<%= link_to "New list", new_list_path %>

app/views/lists/new.html.erb
<h2>Create new list</h2>

<%= render "form", lists: @lists %>
<%= link_to "See all lists", lists_path %>
<%= link_to "See all movies", movies_path %>

app/views/lists/show.html.erb
<h2><%= @list.name %></h2>

<%= link_to "Add a bookmark", new_list_bookmark_path(@list) %>

app/views/movies/_list.html.erb
<div>
  <% movies.each do |movie| %>
    <%= render movie %>
    <p class="container">
      <%= link_to "Show this movie", movie %>
      <%= link_to "Show lists", lists_path %>
    </p>
  <% end %>
</div>

app/views/movies/_movie.html.erb
<%# <div id="<%= dom_id movie %>
<div class="container">
  <p>
    <strong class="">Title:</strong>
    <%= movie.title %>
  </p>

  <p>
    <strong>Overview:</strong>
    <%= movie.overview %>
  </p>

  <p>
    <%= image_tag movie.poster_url, alt: "Poster of the film", width: 200 %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= movie.rating%>
  </p>

</div>

app/views/movies/index.html.erb
<h1>Watch List</h1>

<%# 1 lien vers tous les films, 1 lien vers toutes les listes, en onglet sous la banner ? %>

<h2><%= "Choose your film :" %></h2>

<%= render "movies/list", movies: @movies %>
<%= link_to "See all lists", lists_path %>
<%= link_to "New list", new_list_path %>